import type { NavCategory, PageDef, Tag } from './registry';

const p = (id: string, title: string, tag: Tag, desc: string, load?: PageDef['load']): PageDef => ({
  id, title, tag, desc, load,
});

export const NAV: NavCategory[] = [
  {
    label: 'Cells',
    pages: [
      p('cell-content', 'Cell Content', 'available',
        'How cell values are read, formatted, and rendered into the grid body.',
        () => import('./features/cell-content')),
      p('getting-values', 'Getting Values', 'available', 'Read cell values through the data accessor and grid API.',
        () => import('./features/getting-values')),
      p('text-formatting', 'Text Formatting', 'available', 'Format numbers, text, and dates with renderer options.',
        () => import('./features/text-formatting')),
      p('cell-components', 'Cell Components', 'available', 'Register and use custom cell renderer components.',
        () => import('./features/cell-components')),
      p('cell-data-types', 'Cell Data Types', 'available', 'Column data types drive default rendering and editing.',
        () => import('./features/cell-data-types')),
      p('find', 'Find', 'dev', 'Global search across the grid; match highlighting is in progress.'),
      p('notes', 'Notes', 'roadmap', 'Attach comments/notes to cells.'),
      p('styling-cells', 'Styling Cells', 'available', 'Conditional styles and class rules per cell.',
        () => import('./features/styling-cells')),
      p('highlight-changes', 'Highlighting Changes', 'roadmap', 'Flash cells when their value changes.'),
      p('tooltips', 'Tooltips', 'dev', 'Header tooltips ship today; cell tooltips are partial.'),
      p('expressions', 'Expressions', 'dev', 'Formula-driven cell values (internal engine).'),
      p('view-refresh', 'View Refresh', 'available', 'Refresh cells, headers, and caches on demand.',
        () => import('./features/view-refresh')),
      p('reference-data', 'Reference Data', 'available', 'Map raw values to labels via select/dropdown options.',
        () => import('./features/reference-data')),
      p('cell-text-selection', 'Cell Text Selection', 'available', 'Copy cell text to the clipboard.',
        () => import('./features/cell-text-selection')),
    ],
  },
  {
    label: 'Rows',
    pages: [
      p('row-data', 'Row Data', 'available', 'Supply and replace the grid’s row data.',
        () => import('./features/row-data')),
      p('row-sorting', 'Row Sorting', 'available', 'Single and multi-column sorting.',
        () => import('./features/row-sorting')),
      p('row-numbers', 'Row Numbers', 'dev', 'A dedicated row-index column.'),
      p('row-spanning', 'Row Spanning', 'roadmap', 'Span a cell across multiple rows.'),
      p('row-pinning', 'Row Pinning', 'roadmap', 'Pin rows to the top or bottom.'),
      p('row-height', 'Row Height', 'available', 'Uniform and variable per-row heights.',
        () => import('./features/row-height')),
      p('styling-rows', 'Styling Rows', 'dev', 'Row class and conditional row styles.'),
      p('row-pagination', 'Row Pagination', 'available', 'Page through data with configurable page size.',
        () => import('./features/row-pagination')),
      p('accessing-rows', 'Accessing Rows', 'available', 'Read rows through the store and data API.',
        () => import('./features/accessing-rows')),
      p('row-dragging', 'Row Dragging', 'roadmap', 'Reorder rows via drag, managed or unmanaged.'),
      p('full-width-rows', 'Full Width Rows', 'roadmap', 'Rows that span all columns.'),
    ],
  },
  {
    label: 'Columns',
    pages: [
      p('column-definitions', 'Column Definitions', 'available', 'Configure columns: field, width, renderer, sortable.',
        () => import('./features/column-definitions')),
      p('updating-definitions', 'Updating Definitions', 'available', 'Change column widths, order, visibility, and renderers at runtime.',
        () => import('./features/updating-definitions')),
      p('auto-generate-columns', 'Auto-Generate Columns', 'dev', 'Derive columns from the shape of the data (app-side).',
        () => import('./features/auto-generate-columns')),
      p('column-state', 'Column State', 'available', 'Read and restore column order, width, and visibility.',
        () => import('./features/column-state')),
      p('column-headers', 'Column Headers', 'available', 'Header types and adornments: sortable, filterable, icons, tooltips.',
        () => import('./features/column-headers')),
      p('column-styling', 'Styling & Height', 'dev', 'Header styling via class/style; height is not yet configurable.',
        () => import('./features/column-styling')),
      p('column-custom', 'Custom Components', 'available', 'Build custom header components.',
        () => import('./features/column-custom')),
      p('column-groups', 'Column Groups', 'dev', 'Group model exists; a banded group header row is not yet rendered.',
        () => import('./features/column-groups')),
      p('column-sizing', 'Column Sizing', 'available', 'Resize, auto-fit, and constrain column widths.',
        () => import('./features/column-sizing')),
      p('column-moving', 'Column Moving', 'available', 'Drag or reorder columns programmatically.',
        () => import('./features/column-moving')),
      p('column-pinning', 'Column Pinning', 'dev', 'Pin model exists; sticky/frozen rendering is not yet wired.',
        () => import('./features/column-pinning')),
      p('column-spanning', 'Column Spanning', 'roadmap', 'Span a cell across multiple columns.'),
      p('calculated-columns', 'Calculated Columns', 'dev', 'Derived column values (app-side; formula engine is internal).',
        () => import('./features/calculated-columns')),
    ],
  },
  {
    label: 'Selection',
    pages: [
      p('cell-selection', 'Cell & Range Selection', 'available', 'Select single cells or rectangular ranges.'),
      p('multi-range', 'Multi-Range Selection', 'available', 'Hold to add multiple, non-contiguous ranges.'),
      p('autofill', 'Autofill', 'dev', 'Drag the fill handle to extend a selection.'),
    ],
  },
  {
    label: 'Editing',
    pages: [
      p('editors', 'Cell Editors', 'available', 'Text, number, checkbox, select, dropdown, date editors.',
        () => import('./features/editors')),
      p('edit-lifecycle', 'Edit Lifecycle', 'available', 'Start, commit, cancel, and end events with validation.',
        () => import('./features/edit-lifecycle')),
    ],
  },
  {
    label: 'Updating Data',
    pages: [
      p('set-data', 'Set & Replace Data', 'available', 'Add, remove, and replace rows via setData.',
        () => import('./features/set-data')),
      p('update-cells', 'Update Cells', 'available', 'Targeted updates to specific cells.',
        () => import('./features/update-cells')),
      p('undo-redo', 'Undo / Redo', 'available', 'Reverse and replay data edits.',
        () => import('./features/undo-redo')),
    ],
  },
  {
    label: 'Interactivity',
    pages: [
      p('keyboard', 'Keyboard Navigation', 'available', 'Arrow, page, home/end, enter/tab navigation.'),
      p('touch', 'Touch', 'dev', 'Touch interactions for scroll and drag.'),
      p('aria', 'Accessibility (ARIA)', 'available', 'ARIA roles and attributes via the ARIA manager.'),
      p('rtl', 'RTL Text Direction', 'roadmap', 'Right-to-left layout support.'),
      p('aligned-grids', 'Aligned Grids', 'roadmap', 'Keep two grids column-aligned.'),
      p('localisation', 'Localisation', 'roadmap', 'Translate grid text and formats.'),
    ],
  },
  {
    label: 'Filtering',
    pages: [
      p('quick-filter', 'Quick Filter', 'available', 'Global text search across all columns.',
        () => import('./features/quick-filter')),
      p('text-filter', 'Text Filter', 'available', 'String comparisons: contains, equals, starts/ends with.',
        () => import('./features/text-filter')),
      p('column-filter', 'Column Header Filter', 'available', 'Built-in ▼ filter trigger and popup on each column header.',
        () => import('./features/column-filter')),
      p('number-filter', 'Number Filter', 'available', 'Numeric comparisons: =, ≠, >, <, ≥, ≤, between.',
        () => import('./features/number-filter')),
      p('date-filter', 'Date Filter', 'available', 'Date comparisons: before, after, on, between.',
        () => import('./features/date-filter')),
      p('set-filter', 'Set / Select Filter', 'available', 'Pick from the set of values in a column.',
        () => import('./features/set-filter')),
      p('between-filter', 'Between Filter', 'available', 'Inclusive range across a min and max.',
        () => import('./features/between-filter')),
      p('blank-filter', 'Blank / Not-blank', 'available', 'Filter by presence or absence of a value.',
        () => import('./features/blank-filter')),
      p('advanced-builder', 'Advanced Builder', 'available', 'Compose conditions with AND/OR groups.',
        () => import('./features/advanced-builder')),
      p('filter-export', 'Filter Export', 'available', 'Serialize filters to REST, GraphQL, or SQL.',
        () => import('./features/filter-export')),
      p('backend-filter', 'Backend Filter Mode', 'available', 'Delegate filtering to a server.',
        () => import('./features/backend-filter')),
    ],
  },
  {
    label: 'Advanced',
    pages: [
      p('row-grouping', 'Row Grouping', 'roadmap', 'Group rows by column values.'),
      p('aggregation', 'Aggregation', 'dev', 'Column aggregates via ColumnStore / segment tree.'),
      p('formulas', 'Formulas', 'dev', 'Spreadsheet-style formula evaluation.'),
      p('pivoting', 'Pivoting', 'roadmap', 'Pivot rows into columns.'),
      p('tree-data', 'Tree Data', 'roadmap', 'Hierarchical, expandable rows.'),
      p('master-detail', 'Master / Detail', 'roadmap', 'Expand a row into a detail grid.'),
    ],
  },
  {
    label: 'Accessories',
    pages: [
      p('server-side', 'Server-Side Data', 'available', 'Backend data mode via onDataRequest.'),
      p('import-export', 'Import & Export', 'dev', 'CSV export ships; import is planned.'),
      p('state-lifecycle', 'State & Lifecycle', 'available', 'Grid state, lifecycle plugin, and store.'),
      p('performance', 'Performance', 'available', 'Virtual scrolling over very large datasets.'),
      p('loading-states', 'Loading States', 'available', 'Simple, animated, modern, skeleton, overlay.'),
      p('themes', 'Themes', 'available', 'Eight built-in grid themes.'),
    ],
  },
];
